### ISSUE TITLE
Name filter methodology/strategy?

### ISSUE THREAD

**Issue by dhyanKaro** [LanderTome/numerologyCalculator#1]
I like the name searching you have here, but I'm not sure what numbers to filter for in Full, Vowels, Consonants, etc.
What's the logic or strategy there? Say I know the birthdate (i.e. life path number), then is that my starting point? Or what else do you take into account?

**Comment by LanderTome** [comment]
Sorry for the late reply. Holidays. Name searching and date searching are two different things. When you provide numbers for the name search you are telling the program that you only want names that will have those numbers when you calculate the numerological values. _Note: you can use negative numbers to indicate that you would accept any number except the provided negative numbers._

The point is that you may know that you want a name to have a certain numerological property; ie the vowels add up to a master number like 11. Providing that information allows the returned names to be filtered so they only include matches that fit the criteria.

Date searches work similarly, but there is a different set of criteria for filtering. 

Check out the proof of concept website I have at [mysticalriver.com](https://numerology.mysticalriver.com). It has an interface that will probably help you understand what it is doing.

**Comment by dhyanKaro** [comment]
Thanks. I guess I just don't know which numbers to filter for. Ie if the
life path (dob) turned out to be 8 then maybe I could try to get vowels &
consonants that are also 8?
The filtering is great, just not sure what to filter to.

**Comment by LanderTome** [comment]
You're kind of supposed to come at this name numerology search with your goal already in mind. There isn't really anything that tells what you should want. You should sort of already know what you want and then search for that. 

Many people like to have master numbers (11,22,33,etc) in their chart because they are rare, so those are good numbers to filter on. If you do enough research then it is possible to discover what numbers when combined with your birthdate and other factors will result in very positive numerological interpretations. I, unfortunately, don't have a way to do that for you. 

Check out the website, though. Do a couple of searches with the number filters blank; ie "Michael ? Thompson". This is will just return all names and numbers. Then click on the resulting number links in the tables. You will be provided with some numerological interpretations that could help you start to get an idea of what numbers you like. Then you can refine your searches based on that.

**Comment by dhyanKaro** [comment]
Thanks, it's interesting.
About the site, I was searching around which led me to your Go library first, so I had to download and learn Golang then figure out how to deal with the database, then finally got it working... then later noticed there was a website :) Ha.
It's good though. 👍
